spring:
  application:
    name: Master Java Backend Test

server:
  port: 8004

player:
  name: LightCodeSETest
  age: 22
  maps: {k1: v1, k2: v2}
  lists:
    - list1
    - list2
  isActive: true
  birth: 2002/01/01