spring:
  application:
    name: Master Java Backend Dev

server:
  port: 8002

player:
  name: LightCodeSEDev
  age: 22
  maps: {k1: v1, k2: v2}
  lists:
    - list1
    - list2
  isActive: true
  birth: 2002/01/01